apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
      slack_api_url: 'https://hooks.slack.com/services/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'
    route:
       group_wait: 10s
       group_interval: 30s
       repeat_interval: 30m
       receiver: "slack"
       routes:
         - receiver: "slack"
           group_wait: 10s
           match_re:
             severity: critical|warning
           continue: true
    receivers:
     - name: "slack"
       slack_configs:
         - send_resolved: true
           channel: '#dvs_06_notifications'
           text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: alertmanager
    meta.helm.sh/release-namespace: 06-d-pashkov
  creationTimestamp: "2022-10-25T08:07:09Z"
  labels:
    app: alertmanager
    app.kubernetes.io/managed-by: Helm
  name: alertmanager
  namespace: 06-d-pashkov
  resourceVersion: "296562495"
  uid: 3c708a95-5743-4fb5-9c10-045bbe2fff73
