---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: ingress-example-tls
      hosts: 
        - {{ .Values.ingress.tls.hosts }}
  rules:
  - host: {{ .Values.ingress.rules.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.ingress.rootpath.port.number }}
