---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.proxy_pass_Name }}
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.proxy_pass_Port }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: backend
