stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  environment:
    name: kubernetes
    url: https://06-d-pashkov.k8s.praktikum-services.tech
  before_script:
    - mkdir -p ~/.kube
    - echo ${kubeconfig} | base64 -d > ~/.kube/config
    - KUBECONFIG=~/.kube/config
    - export KUBECONFIG
    - echo "$KUBECONFIG"
    - kubectl config view
    - kubectl config get-contexts
    - kubectl get all
    - kubectl get no
    - kubectl get po
    - kubectl cluster-info
  script:
#    - kubectl apply -f kubernetes/backend/
#    - kubectl apply -f kubernetes/backend-report/
#    - kubectl apply -f kubernetes/frontend/
    - rm -f ~/.kube/config
    - echo "$KUBECONFIG"
