# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  vault_token: {{ .Values.global.vault_token }}
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  labels: 
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  .dockerconfigjson: {{ .Values.global.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
